norns/urls.py
"""
URL configuration for norns project.
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Admin
    path("mstr/", admin.site.urls, name="admin"),
    # 3rd Party
    path("accounts/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    # Local
    path("accounts/", include("accounts.urls")),
    path("parties/", include("parties.urls")),
    path("", include("pages.urls")),
]

parties/urls.py
"""URLs for parties app"""

from django.urls import path

from .views import (
    PartyCreateView,
    PartyDeleteView,
    PartyDetailView,
    PartyListViewJoined,
    PartyListViewOwned,
    PartyUpdateView,
    RemoveMemberView,
)

urlpatterns = [
    path("member_remove/<int:pk>/", RemoveMemberView.as_view(), name="member_remove"),
    path("<int:pk>/delete/", PartyDeleteView.as_view(), name="party_delete"),
    path("<int:pk>/", PartyDetailView.as_view(), name="party_detail"),
    path("<int:pk>/edit/", PartyUpdateView.as_view(), name="party_edit"),
    path("joined/", PartyListViewJoined.as_view(), name="party_list_joined"),
    path("owned/", PartyListViewOwned.as_view(), name="party_list_owned"),
    path("new/", PartyCreateView.as_view(), name="party_new"),
    path("", PartyListViewJoined.as_view(), name="party_list_joined"),
]

parties/models.py
"""Models for parties app"""

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class SoftDeleteQuerySet(models.query.QuerySet):
    """Custom queryset for soft deleted objects"""

    def delete(self):
        """Soft deletes an object. i.e. sets deleted_at to current timestamp"""
        return super().update(deletd_at=now())

    def hard_delete(self):
        """Hard deletes an object. i.e. removes the record from the database"""
        return super().delete()

    def active(self):
        """Returns only active objects"""
        return self.filter(deleted_at=None)

    def inactive(self):
        """Returns only inactive objects"""
        return self.exclude(deleted_at=None)


class SoftDeleteManager(models.Manager):
    """Manager for soft deletion of objects"""

    def __init__(self, *args, **kwargs):
        self.active_only = kwargs.pop("active_only", True)
        super().__init__(*args, **kwargs)

    def get_queryset(self):
        """Custom queryset for soft deleted objects"""
        if self.active_only:
            return SoftDeleteQuerySet(self.model).filter(deleted_at=None)
        return SoftDeleteQuerySet(self.model)

    def hard_delete(self):
        """Queryset for hard deletion of objects"""
        return self.get_queryset().hard_delete()


class SoftDeleteModel(models.Model):
    """Base model for objects that require soft deletion"""

    deleted_at = models.DateTimeField(null=True, blank=True)

    all_objects = SoftDeleteManager(active_only=False)
    objects = SoftDeleteManager()

    class Meta:
        """Sets model as abstract"""

        abstract = True

    def delete(self, *args, **kwargs):
        """Soft deletes object by setting deleted_at to the current timestamp"""
        self.deleted_at = now()
        self.save(*args, **kwargs)

    def hard_delete(self, *args, **kwargs):
        """Hard deletes an object from the database"""
        super().delete(*args, **kwargs)


class Party(SoftDeleteModel):
    """Party model"""

    name = models.CharField(max_length=100)
    description = MarkdownxField()
    dm = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta class."""

        verbose_name_plural = "Parties"

    def __str__(self):
        return str(self.name)

    @property
    def formatted_description(self):
        """Formats markdown as HTML"""
        return markdownify(self.description)

    def get_absolute_url(self):
        """Returns absolute URL for parties detail view"""
        return reverse("party_detail", kwargs={"pk": self.pk})


class PartyMember(SoftDeleteModel):
    """Member model"""

    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    character_name = models.CharField(max_length=100, default="name")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.party.name + " - " + str(self.user) + " - " + self.character_name

    def get_absolute_url(self):
        """Returns absolute URL for party members detail view"""
        return reverse("party_member_detail", kwargs={"pk": self.pk})


class PartyBlogPost(SoftDeleteModel):
    """Blog post model for parties"""

    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    content = MarkdownxField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    @property
    def formatted_content(self):
        """Formats markdown as HTML"""
        return markdownify(self.content)

    def get_absolute_url(self):
        """Returns absolute URL for parties detail view"""
        return reverse("party_blog_post", kwargs={"pk": self.pk})

parties/forms.py
"""Forms for parties app"""

from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Party, PartyMember


class PartyMemberForm(forms.ModelForm):
    """Form to add a party member"""

    class Meta:
        """Meta class."""

        model = PartyMember
        fields = ("user", "character_name")


class NewPartyForm(forms.ModelForm):
    """Form to add a party member"""

    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        """Meta class."""

        model = Party
        fields = ("name", "description")

parties/views.py
"""Views for parties app"""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    ListView,
    UpdateView,
)
from django.views.generic.detail import SingleObjectMixin

from .forms import PartyMemberForm
from .models import Party, PartyBlogPost, PartyMember


class MemberGet(DetailView):
    """Returns member for party"""

    model = Party
    template_name = "parties/party_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = PartyMemberForm()
        return context


class AddPartyMember(SingleObjectMixin, FormView):
    """View to add a party member at the bottom of the party detail page"""

    model = Party
    form_class = PartyMemberForm
    template_name = "parties/party_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = (  # pylint: disable=attribute-defined-outside-init
            self.get_object()
        )
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        party_member = form.save(commit=False)
        party_member.party = self.object
        party_member.save()
        return super().form_valid(form)

    def get_success_url(self):
        party = self.object
        return reverse("party_detail", kwargs={"pk": party.pk})


class PartyDetailView(LoginRequiredMixin, View):
    """View for party details"""

    def get(self, request, *args, **kwargs):
        """Returns details of party for GET methods"""
        view = MemberGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """Returns details of party for POST methods"""
        view = AddPartyMember.as_view()
        return view(request, *args, **kwargs)


class PartyListViewJoined(LoginRequiredMixin, ListView):
    """List of parties the user is a member in"""

    model = Party
    template_name = "parties/party_list_joined.html"
    ordering = ["name"]

    def get_queryset(self):
        queryset = super().get_queryset().distinct()
        return queryset.filter(deleted_at=None, partymember__user=self.request.user)


class PartyListViewOwned(LoginRequiredMixin, ListView):
    """List of parties the user is a member in"""

    model = Party
    template_name = "parties/party_list_owned.html"
    ordering = ["name"]

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(deleted_at=None, dm=self.request.user)


class PartyUpdateView(LoginRequiredMixin, UpdateView):
    """Update parties view"""

    model = Party
    fields = ("description",)
    template_name = "parties/party_edit.html"

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(dm=self.request.user)


class PartyDeleteView(LoginRequiredMixin, DeleteView):
    """Delete parties view"""

    model = Party
    template_name = "parties/party_delete.html"
    success_url = reverse_lazy("party_list")

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(dm=self.request.user)


class PartyCreateView(LoginRequiredMixin, CreateView):
    """Create new party"""

    model = Party
    template_name = "parties/party_new.html"
    fields = (
        "name",
        "description",
    )

    def form_valid(self, form):
        form.instance.dm = self.request.user
        return super().form_valid(form)


class RemoveMemberView(LoginRequiredMixin, DeleteView):
    """Delete party member view"""

    model = PartyMember
    template_name = "parties/member_remove.html"

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(party__dm=self.request.user)

    def get_success_url(self):
        party = self.object.party
        return reverse("party_detail", kwargs={"pk": party.pk})


class PartyBlogListView(LoginRequiredMixin, ListView):
    """All blog posts for the party"""

    model = PartyBlogPost
    template_name = "parties/blog/party_blog_list.html"
    ordering = "-created_at"

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        return queryset.filter(
            deleted_at=None,
            party__partymember__user=self.request.user,
            party__partymember__deleted_at=None,
        )

templates/parties/member_remove.html
{% extends "base.html" %}
{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to remove "{{ partymember.character_name }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/parties/party_delete.html
{% extends "base.html" %}
{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ party.name }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/parties/party_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="party-detail">
        <h2>{{ object.name }}</h2>
        <p>{{ object.formatted_description|safe }}</p>
    </div>
    <hr>
    <h4>Members ({{ object.partymember_set.count }})</h4>
    {% for member in party.partymember_set.all %}
        <p>
            {{ member.character_name }} - ({{ member.user.username }})
            {% if user == party.dm %}
                <a class="btn btn-danger btn-sm"
                   href="{% url "member_remove" member.pk %}"
                   role="button">Remove</a>
            {% endif %}
        </p>
    {% endfor %}
    {% if party.dm == request.user %}
        <h4>Add a party member</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>
        <hr>
        <div>
            <p>
                <a class="btn btn-primary btn-lg"
                   href="{% url 'party_edit' party.pk %}"
                   role="button">Edit</a>
                <a class="btn btn-danger btn-lg"
                   href="{% url 'party_delete' party.pk %}"
                   role="button">Delete</a>
            </p>
        </div>
    {% endif %}
    <hr>
{% endblock content %}

templates/parties/party_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>
{% endblock content %}

templates/parties/party_list.html
{% extends "base.html" %}
{% block title %}
{% endblock title %}
{% block content %}
    <h2>
        {% block pageheader %}
        {% endblock pageheader %}
    </h2>
    {% for party in party_list %}
        <div class="card">
            <h3 class="card-header">
                <span class="float-start">
                    <a class="fw-bold link-dark text-decoration-none"
                       href="{{ party.get_absolute_url }}">{{ party.name }}</a>
                </span>
                <span class="text-muted float-end">{{ party.dm }}</span>
            </h3>
            <div class="card-body">{{ party.description }}</div>
        </div>
        <br />
    {% endfor %}
{% endblock content %}

templates/parties/party_list_joined.html
{% extends "parties/party_list.html" %}
{% block title %}
    Joined Parties
{% endblock title %}
{% block pageheader %}
    Joined Parties
{% endblock pageheader %}

templates/parties/party_list_owned.html
{% extends "parties/party_list.html" %}
{% block title %}
    Owned Parties
{% endblock title %}
{% block pageheader %}
    Owned Parties
{% endblock pageheader %}

templates/parties/party_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>New party</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock content %}